python -u train_generative.py \
--dset_name eth  \
--obs_len 8 \
--pred_len 12 \
--delim tab \
--model_type generative_spatial_temporal \
--domain_type learnable \
--domain_parameter 5 \
--batch_size 32 \
--noise_type gaussian \
--num_epochs 200 \
--best_k 20 \
--num_traj 20 \
--weight_sim 0 \
--lr_g 0.001 \
--lr_d 0.001 \
--delta_bearing 30 \
--delta_heading 30 \
