python -u \
train_generative.py \
--dset_name zara1 \
--obs_len 8 \
--pred_len 12 \
--delim "\t" \
--model_type generative_spatial_temporal \
--domain_parameter 2 \
--batch_size 32 \
--noise_type uniform \
--noise_mix_type sample \
--num_epochs 300 \
--eval_batch_size 128 \
--best_k 1 \
--scheduler \
--l2_loss_weight 0.5 \
--num_traj 20 \
--l 0 \
--lr_g 1e-03 \
--lr_d 1e-03 \
--num_iter 5 \
--delta_bearing 30 \
--delta_heading 30 \
--encoder_dim 32 \
--decoder_dim 32 \
--attention_dim 32 \
--embedding_dim 16 \
--d_type local \
--d_spatial \
