python -u train_deterministic.py \
--dset_name univ \
--obs_len 8 \
--pred_len 12 \
--delim "\t" \
--model_type scene_spatial_temporal \
--scheduler \
--domain_parameter 5 \
--batch_size 32 \
--eval_batch_size 32 \
--num_epochs 200 \
--delta_bearing 30 \
--delta_heading 30 \
--encoder_dim 32 \
--decoder_dim 32 \
--attention_dim 32 \
--embedding_dim 16 \
--lr 1e-03 \
--gpu_id 3 \
--use_scene_context 
